theme: jekyll-theme-midnight
title: Soumyanil Biswas
description: Cyber Security Enthusiast
logo: https://raw.githubusercontent.com/reveng007/Pages/main/assets/img/big_pic_bg.jpg
show_downloads: false
